apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-playground
  template:
    metadata:
      labels:
        app: vllm-playground
    spec:
      containers:
        - name: streamlit
          image: gcr.io/blog-180218/vllm-playground:latest
          ports:
            - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  selector:
    app: vllm-playground
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: ClusterIP
